### ISSUE TITLE
clip_x11.cpp is missing #include <functional>

### ISSUE THREAD

**Issue by SSBMTonberry** [dacap/clip#12]
Hey!
I just downloaded your lib, and it wouldn't compile. I noticed it was complaining about std::function related stuff, so I added 

`#include <functional> `

That solved the problem for me. 

Cheers!

**Comment by dacap** [comment]
Hi there! It's strange because this issue should be solved with f8e089dcedc12a1a6046d3142e741ec5d0de923d already, the same issue as in #11. Did you compile the [master branch](https://github.com/dacap/clip/blob/master/clip_x11.cpp#L18)?

**Comment by SSBMTonberry** [comment]
@dacap You're right. I must have downloaded it some time ago and opened wrong folder when extracting the newest version today. Just tried to delete the current folder, then extract the tar.gz, then try to compile, and it worked. Guess it was a false alarm. Sorry about that.

**Comment by dacap** [comment]
Don't worry, thanks for reporting the issue 👍
