### ISSUE TITLE
Add support to copy/paste text on Linux

### ISSUE THREAD

**Issue by dacap** [dacap/clip#3]

**Comment by Kerndog73** [comment]
@dacap Are you planning on implementing this or have you abandoned this project? I'd really like to see this feature.

**Comment by dacap** [comment]
This is planned and this project is not abandoned. There is [a fork](https://github.com/Azure-Vani/clip) by @Azure-Vani with some progress done, but I think that in a couple of weeks I will start the Linux support from scratch.

**Comment by darkdragon-001** [comment]
I just stumbled over [jtanx/libclipboard](https://github.com/jtanx/libclipboard) with an [explanatory blog post](https://jtanx.github.io/2016/08/19/a-cross-platform-clipboard-library/).

**Comment by dacap** [comment]
Thanks @darkdragon-001, I'll take a look to that later. I wasn't able to work on the Linux port yet, but next week I've plans to work on [Aseprite](https://github.com/aseprite/aseprite) Linux port so the clip library will have some progress on that aspect too. 

At the moment there is a behavior on Linux where the clipboard content is stored/provided by the running process that "pasted" content on it. My worry is how to keep this content alive even when your process die. A possible solution would be to start a new process at the exit of the existent one just to keep the clipboard data until we lost it.

**Comment by dacap** [comment]
I've just started working on this issue in the x11 branch: https://github.com/dacap/clip/tree/x11
