### ISSUE TITLE
clip/clip_win_wic.h:68:12: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization

### ISSUE THREAD

**Issue by API-Beast** [dacap/clip#32]
```
clip/clip_win_wic.h:68:12: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
```

https://github.com/dacap/clip/blob/0a961d75f4ffbf3bf24d707cfa66d6bcc1c295be/clip_win_wic.h#L68

When compiling with GCC on Windows. Obvious fix is to return false; instead.

**Comment by dacap** [comment]
Oh sorry about that, thanks for reporting, I'll fix it just right now.
