### ISSUE TITLE
clip::lock::get_image sometimes fails to get clipboard data.

### ISSUE THREAD

**Issue by API-Beast** [dacap/clip#36]
In clip_win.cpp::90 `if(IsClipboardFormatAvailable(CF_DIBV5))` succeeds but `GetClipboardData(CF_DIBV5)` fails, returning a null pointer. This will result in a crash with a "Image format not supported" exception. Calling locked() on the lock also returns true.

Using clip::get_image(img) directly works properly? Which is weird since those functions also use locks internally.

----------------------

~~To test, change the show_image example change lines 48 and 49 to use a lock:~~
```cpp
  clip::lock lock; clip::image img;
  if (!lock.get_image(img)) {
```

~~Running the changed test will crash with a "Image format not supported" exception.~~

Unfortunately I can't reproduce it in the show_image example and I'm still unsure what the reason for that is.

**Comment by dacap** [comment]
Hi there @API-Beast, what program are you trying to copy from? can you share the code? I see that the example or even clip::get_image() check for clip::lock::is_convertible(image_format()) first, so that might be the reason because the exception is not throwing in the example.

**Comment by dacap** [comment]
After a chat with @API-Beast it looks as a problem of double-locking the clipboard when mixing the high-level API (which use a lock on each call) and the low-level API (the lock itself). E.g.

```c++
using namespace clip;
lock l;
if (has(image_format())) { // has() tries to re-lock the clipboard (l.is_convertible() must be used here)
  l.get_image(...);
} 
```

This cannot be done. The high-level API is meant to be used when we don't care about locks, but mixing both APIs will not work.
