### ISSUE TITLE
indefinite reference to « clip::set_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »

### ISSUE THREAD

**Issue by titicplusplus** [dacap/clip#40]
Hi,

When I compile my code, with this line : 
`g++ text.cpp curseur.cpp main.cpp -o editeur -lsfml-network -lsfml-audio  -lsfml-graphics -lsfml-window -lsfml-system` 

my file is :

      #include <SFML/Graphics.hpp>
      #include <SFML/System.hpp>
      #include <unistd.h>
      #include <iostream>
      #include <SFML/Window.hpp>
      
      #include <string>
      
      #include "text.hpp"
      #include "curseur.hpp"
      
      //#include <libclipboard.h>
      
      #include "build/clip/clip.h"
      
      int main()
      {
	      clip::set_text("Hello World");
      
              //////// my code ////////////////////////
      }

And so, I have this error : 

      /usr/bin/ld : /tmp/cc7b6W55.o : in the function « main » :
      main.cpp:(.text+0x58) : indefinite reference to « clip::set_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »
      collect2: error: ld returned 1 exit status

However, I had been compiled the source code with

    git clone https://github.com/dacap/clip
    mkdir build
    cd build
    cmake-gui
    make

So I can't find the linking word to add to my command line 
      `g++  text.cpp curseur.cpp main.cpp -o editeur -lsfml-network -lsfml-audio  -lsfml-graphics -lsfml-window -lsfml-system -???????`

So, can someone help me?
Thank you in advance

**Comment by dacap** [comment]
Hi @titicplusplus, you have to link your program with the clip library e.g. specifying `-lclip` in the command line.

**Comment by titicplusplus** [comment]
ok, thank you it's work
