### ISSUE TITLE
how to save image to file?

### ISSUE THREAD

**Issue by github357** [dacap/clip#42]
i get bmp image from clip , but how to save this image to file, in  windows???

**Comment by dacap** [comment]
Hi @github357, actually this library doesn't support saving images to disk (officially / with its public API), but on Windows you could see (include) the `clip_win_wic.h` file and use the [`clip::win::write_png()` function](https://github.com/dacap/clip/blob/f13c9656d51482c1908c9a551ce76f9450b7bd55/clip_win_wic.h#L142) as an example for your own code to write png files to disk.
