### ISSUE TITLE
Did I install it wrong?

### ISSUE THREAD

**Issue by Aze1337** [dacap/clip#44]
Hey there! my first time trying a c++ library, I could "#include "clip.h" and write some code but I get those two errors
![image](https://user-images.githubusercontent.com/76887650/116823909-400b8a00-ab55-11eb-89de-4eea34f6e0e8.png)
this is the code im trying to run
![image](https://user-images.githubusercontent.com/76887650/116823918-4ac61f00-ab55-11eb-9a33-bbc38f5abdcb.png)
anyone know what im doing wrong?

thanks very much

**Comment by dacap** [comment]
Hi @Aze1337, you need to link your `.exe` with the `clip.lib`.

You can see an example in the Wiki with cmake: https://github.com/dacap/clip/wiki#how-to-use-it

I hope it helps!

**Comment by Aze1337** [comment]
Hello @dacap Thank you a lot for your response!

I'm still unsure how to do it - I've followed this https://en.wikibooks.org/wiki/C%2B%2B_Programming/Compiler/Linker/Libraries/Configuring_Visual_Studio
![image](https://user-images.githubusercontent.com/76887650/116924614-2128f880-ac26-11eb-9827-c6f7db5e3dd9.png)

I have put this folder path here, 
![image](https://user-images.githubusercontent.com/76887650/116925002-9e546d80-ac26-11eb-9235-ca1c11199c2a.png)



and this folder
![image](https://user-images.githubusercontent.com/76887650/116925030-aa402f80-ac26-11eb-892b-fa620e97a0bd.png)

in here 
![image](https://user-images.githubusercontent.com/76887650/116925057-b1673d80-ac26-11eb-92ac-f9ccc5cde344.png)


but whenever I compile, it gets me those errors
![image](https://user-images.githubusercontent.com/76887650/116925095-bfb55980-ac26-11eb-85ee-0ba546bf8108.png)


do you possibly know what I'm doing wrong ? thanks again

**Comment by dacap** [comment]
You've configured the directories but didn't specify the clip.lib as an input to the linker (check the Linker > Input), anyway I don't remember the Visual Studio settings, but I think there should be the field to add the clip.lib as an input to the linker.

**Comment by Aze1337** [comment]
just specified it there
![image](https://user-images.githubusercontent.com/76887650/116927547-cf826d00-ac29-11eb-90dc-ce50f4474f07.png)

less errors now but still not sure what else to do
![image](https://user-images.githubusercontent.com/76887650/116927608-e032e300-ac29-11eb-8a25-5b977f5d3085.png)

**Comment by dacap** [comment]
Oh sorry about that, you have to link to `shlwapi.lib` too (add that file in the additional dependencies field too).

Generally clip is made to be used with cmake (so dependencies are included automatically), so this manual configuration is not expected in the regular use case, but in your case, you will need to specify the dependencies manually.

**Comment by Aze1337** [comment]
> Oh sorry about that, you have to link to `shlwapi.lib` too (add that file in the additional dependencies field too).
> 
> Generally clip is made to be used with cmake (so dependencies are included automatically), so this manual configuration is not expected in the regular use case, but in your case, you will need to specify the dependencies manually.

Thank you very much for your help! I can compile & run just fine :D
