### ISSUE TITLE
xcb.h not found / Linux needs xcb library

### ISSUE THREAD

**Issue by Creapermann** [dacap/clip#46]
I pulled the clip library and tried to compile it, but in "clip_x11.cpp" i m getting an error including the #include <xcb/xcb.h>. How should i fix this? i find no file called "xcb.h" in this repo

**Comment by dacap** [comment]
Hi @Creapermann, the xcb.h header file is included in the xcb library. I think this library is in libx11-dev, libX11-devel, or libx11 packages of your Linux distro.

**Comment by Creapermann** [comment]
@dacap so i need to get a Extertal library ?

**Comment by dacap** [comment]
You need the base libraries used to develop X11 applications (X11 and xcb are the lowest common denominators for GUI apps on Linux, they are like the libc for the UI, which is other dependency almost all programs need).
