### ISSUE TITLE
Getting linking error on building

### ISSUE THREAD

**Issue by Creapermann** [dacap/clip#47]
I m compiling like usual and linking a library (checked the linking and including like 3 times) but i get this error: 

clip.lib(clip_win.obj) : error LNK2019: unresolved external symbol __imp_SHCreateMemStream referenced in function "bool __cdecl clip::win::read_png(unsigned char const *,unsigned int,class clip::image *,struct clip::image_spec *)" (?read_png@win@clip@@YA_NPEBEIPEAVimage@2@PEAUimage_spec@2@@Z)

. Any idea why this could be? i have no clue

**Comment by dacap** [comment]
Hi there :wave: you need to link your .exe with `shlwapi.lib` library, we include that library in our CMakeLists.txt:

https://github.com/dacap/clip/blob/a65a9e543e9a270bb7c58789d15d027bbd8efb2a/CMakeLists.txt#L68

If you are using cmake that shouldn't be a problem. How are you building/linking your program?

**Comment by Creapermann** [comment]
> 
> 
> Hi there 👋 you need to link your .exe with `shlwapi.lib` library, we include that library in our CMakeLists.txt:
> 
> https://github.com/dacap/clip/blob/a65a9e543e9a270bb7c58789d15d027bbd8efb2a/CMakeLists.txt#L68
> 
> If you are using cmake that shouldn't be a problem. How are you building/linking your program?

I m not working with cmake, i m using the vs19 build system. Where can i get "shlwapi.lib"  from?

**Comment by Creapermann** [comment]
> 
> 
> Hi there 👋 you need to link your .exe with `shlwapi.lib` library, we include that library in our CMakeLists.txt:
> 
> https://github.com/dacap/clip/blob/a65a9e543e9a270bb7c58789d15d027bbd8efb2a/CMakeLists.txt#L68
> 
> If you are using cmake that shouldn't be a problem. How are you building/linking your program?

@dacap, tried multiple versions of that .dll file, nothing works. Do you have an idea?

**Comment by dacap** [comment]
You have to add "shlwapi.lib" in the same place where (e.g.) user32.lib is included. In the *project properties > Configuration Properties > Linker > Input > Additional Dependencies*

**Comment by Creapermann** [comment]
oh so i just need to link it?

**Comment by dacap** [comment]
Yes

**Comment by Creapermann** [comment]
> 
> 
> Yes

Its all working, thanks!
