### ISSUE TITLE
Get data from clipboard?

### ISSUE THREAD

**Issue by Creapermann** [dacap/clip#48]
I checked out the existing functions the clip:: namespace has but i couldnt find anything which would get for example the first entry of the clipboard into string.
Does anything like this exist, if yes how is it called and how would I use it?
Do i need another library for it?

Thanks in advance.

**Comment by Creapermann** [comment]
@dacap any idea?

**Comment by Akaame** [comment]
Hello,

Does not `get_text` cut it or am I missing something in your problem statement?
