### ISSUE TITLE
Custom formats

### ISSUE THREAD

**Issue by azertyalex** [dacap/clip#54]
I'm trying to write other formats to the clipboard for example `image/jpeg` or  `image/jpg` but pasting anywhere does not result in a jpeg being pasted.

code:
```c++
#include <cassert>
#include <fstream>
#include <iostream>
#include "clip.h"

int main() {
  clip::format int_format = clip::register_format("image/jpeg");
  std::ifstream file("lala.jpg");
  file.get();
  std::string line;
  std::string longline;

  while (std::getline(file, line)) {
    longline.append(line);
  }

  clip::lock l;
  if (l.locked()) {
    l.clear();
    return l.set_data(int_format, longline.c_str(), longline.size());
  } else {
    return false;
  }
}
```

I also tried hacking it in by getting the atom for image/jpeg  and editing https://github.com/dacap/clip/blob/main/clip_x11.cpp#L257 so that m_data always sets a jpeg regardless of me calling a set_data with the text/plain atom. But nothing seems to work.

**Comment by azertyalex** [comment]
It seems I can put anything into "image/jpeg".
```bash
xclip -sel clip -t "image/jpeg" -o
file:///home/amol/Code/Varia/clip/build/examples/lala.jpg
```

But using my own custom schemes do not result in anything, which is a shame because I need to set `text/uri-list`

**Comment by dacap** [comment]
Hi @azertyalex, I think it should work, but you should copy the binary data just exactly as it is (don't use getline() because it is suited only for text-based data and might modify the final result).

**Comment by dacap** [comment]
On X11, the clipboard is shared directly between programs that owns the clipboard and the one that ask for its content, anyway when the program that own the clipboard selection is closed, it can decide if transfer its data to a possible clipboard manager (if it's available): https://github.com/dacap/clip/blob/c46c49141f72dd753b260eea4e6d7b37413f0ff6/clip_x11.cpp#L122

The selection manager and the SAVE_TARGETS mechanism depends on your Linux distribution/WM. E.g. if the clip library asks to the clipboard manager to save targets, the manager should request to our program the clipboard data and save it.

**Comment by azertyalex** [comment]
I actually do not need a clipboard manager. I just made an example for debugging purposes. I'm using clip.h in a remote browsing situation, and my browser will always be running :) 

Thanks for the help!
