### ISSUE TITLE
Paste from clipboard delay on Linux

### ISSUE THREAD

**Issue by joeyes86** [dacap/clip#57]
In linux, after placing the text in the clipboard (`clip::set_text`) and then trying to paste the text (for example, in Text Editor) manually from the clipboard, the insertion occurs with a large delay (half a minute). At the same time, if you terminate the application that called `set_text`, the copied text is inserted from the clipboard instantly.

**Comment by dacap** [comment]
Hi @joeyes86, it looks like a specific problem when interacting with Text Editor app (gedit), I've tried terminal or emacs and it works correctly. There is something to fix.

**Comment by joeyes86** [comment]
Wow, that was fastest response what I've seen! Thanks a lot!
