### ISSUE TITLE
Question: Is this library thread-safe?

### ISSUE THREAD

**Issue by TheDonsky** [dacap/clip#58]
Hello, I basically want to know if the library is thread-safe or not (I mean within the same application; inter-process will obviously be safe)

**Comment by dacap** [comment]
Hi there @TheDonsky, this library is not thread safe in the way that using it at the same time from multi-threads will bring problems.

Anyway I'm not 100% if all 3 implementations would fully work if you use both APIs ([low level and high level](https://github.com/dacap/clip/wiki/API)) from the non-main (non-UI) thread (i.e. the thread running with the main message loop of events).

**Comment by TheDonsky** [comment]
Hi again, huge thanks for the information and the fast response.

I'll add a 'global clipboard lock' to my project.

As a side note, so far I've tested only on windows without any UI and will need to make it work on Linux too. Mac OS is not my priority for now. And in both those cases, I have a manually created thread managing the Window with no problems so far (If I'm not mistaken, you can even have multiple event threads for both). Will probably run into a few issues when I finally get to build anything MacOS-related, though.
