### ISSUE TITLE
[macOS 10.14+] Compiler warns about deprecated variables

### ISSUE THREAD

**Issue by 607011** [dacap/clip#63]
Change all occurrences of `NS16BitBigEndianBitmapFormat` to `NSBitmapFormatSixteenBitBigEndian`, of `NSAlphaFirstBitmapFormat` to `NSBitmapFormatAlphaFirst`, of `NSAlphaNonpremultipliedBitmapFormat` to `NSBitmapFormatAlphaNonpremultiplied` and so on.

**Comment by dacap** [comment]
Hi @607011, we're targeting macOS 10.9, I'll check if those constants can be used when we target that version and then make the change.

**Comment by 607011** [comment]
Yikes! 10.9 is almost 10 years old. 

Nevertheless, I managed to include your wonderful library in my project: https://github.com/607011/clip2png2clip (currently only tested with macOS 13.2 on an MacBook Air M2) :-)

**Comment by dacap** [comment]
Oh yeah, 10.9 is pretty old, I'm thinking and probably we could update to macOS 10.14 as the minimum platform (which is the one reported in our logs).

Beyond that, I'm glad to see that clip is being useful in projects like clip2png2clip 🍻
