### ISSUE TITLE
Memory "leaks" in Loop

### ISSUE THREAD

**Issue by NekoAsakura** [dacap/clip#64]
Hi, I'm using this library to monitor by clipboard and remove unwanted `'\r'` in silence. But I notice that the `CFString` are not released in each loop, how can I solve it?

Here is my code:
```
#include <string>
#include <thread>
#include <chrono>
#include "clip.h"

using namespace std;

int main() {
    while (true) {
        string new_value;
        if (clip::has(clip::text_format())) {
            clip::get_text(new_value);
            if (new_value.find('\r') != string::npos) {
                replace(new_value.begin(), new_value.end(), '\r', ' ');
                clip::set_text(new_value);
            }
        }
        this_thread::sleep_for(chrono::milliseconds(1000));
    }
    return 0;
}

```

**Comment by dacap** [comment]
Hi @NekoAsakura thanks a lot for reporting this bug. I've just pushed a fix to `main`, you can give a try.

**Comment by NekoAsakura** [comment]
Thank you for letting me know! I appreciate your quick response in fixing the bug.
