### ISSUE TITLE
Cann't build this code on Windows 7 VS2015

### ISSUE THREAD

**Issue by toby20130333** [dacap/clip#7]
Hi 
I cann't build this sourcecode on windows 7
get some error  about namespace.

**Comment by dacap** [comment]
Hi there, could you please include the errors/console output here in this issue?

**Comment by toby20130333** [comment]
clip_win.obj : error LNK2005: "public: __thiscall clip::lock::impl::impl(void *)" (??0impl@lock@clip@@QAE@PAX@Z) already defined in clip_none.obj 
clip_win.obj : error LNK2005: "public: __thiscall clip::lock::impl::~impl(void)" (??1impl@lock@clip@@QAE@XZ) already defined in clip_none.obj
clip_win.obj : error LNK2005: "public: bool __thiscall clip::lock::impl::clear(void)" (?clear@impl@lock@clip@@QAE_NXZ)already defined in clip_none.obj 
.......
........

**Comment by toby20130333** [comment]
I am sorry,It's my fault,I use Qtcreator to build on windows We must remove clip_none.cpp,and built it ok on win7 vs2015
thx

**Comment by dacap** [comment]
No problem, I'm glad to hear that 👍
