### ISSUE TITLE
[x-issue] Potential EoP in Windows clipboard libraries (MS15-097)

### ISSUE THREAD

**Issue by oberrich** [dacap/clip#71]
See [Potential EoP in Windows clipboard libraries (MS15-097)](https://github.com/oberrich/x-issues/issues/1) for discussion.

**Comment by oberrich** [comment]
**Proposed fix**: Implement [`AnonymousImpersonator` scope-guard](https://chromium.googlesource.com/chromium/src/+/refs/tags/125.0.6422.1/ui/base/clipboard/clipboard_win.cc#55) and instantiate here:
https://github.com/dacap/clip/blob/42e0d7c288f05f872095f0026fd8218216250155/clip_win.cpp#L74

**Comment by dacap** [comment]
Thanks for the report @oberrich, I'll try to push a fix ASAP. It looks like an issue only if the running process has elevated privilegies and it creates or loads a third-party child process/library, in that case that process/library could get the elevated token.

**Comment by oberrich** [comment]
@dacap I have created a PR to implement a C++11 version of the Chromium implementation: Instead of deleting copy operators explicitly, I've `must_revert` `const`, this implicitly deletes the copy constructor in 11.
